# Generated by Django 4.0 on 2021-12-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions_of_figures', models.CharField(default='rnbqkbnrppppppppxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxPPPPPPPPRNBQKBNR', max_length=64)),
                ('step_count', models.DecimalField(decimal_places=0, default='', max_digits=10)),
                ('player_name', models.CharField(default='', max_length=20)),
                ('white_or_black', models.CharField(default='New', max_length=5)),
                ('date_of_step', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
